language: cpp
sudo: required
services:
  - docker


jobs:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libboost-program-options-dev
      install:
        - echo "test stage - cmake build install"
      script:
        - echo "test stage - cmake script"

    - os: linux
      install:
        - echo "test2 stage - docker build install"
      script:
        - echo "test2 stage - docker script"
        - docker image ls -a
    
    - stage: deploy
    - os: linux
      install: 
        - echo "deploy stage - install"
      script:
        - echo "deploy stage - script"
